package com.kycdao.android.sdk.model

enum class State {
    CONNECT_WALLET,
    SESSION_REQUIRED,
    LOGIN_REQUIRED,
    USER_INFORMATION_REQUIRED,
    WAIT_EMAIL_CONFIRMED,
    IDENTITY_VERIFICATION,
    POLL_IDENTITY_VERIFICATION_RESULT,
    NFT_IMAGE_SELECTION,
    WAITING_FOR_MINTING_AUTHORISATION,
    CALCULATE_FEE,
    MINTING,
    CHECK_MINTING,
    POST_MINT_TOKEN_ID,
    COMPLETED
}